In [13]:
In this checkpoint, we are going to work on the billing history of the Tunisian electricity and gas company and apply what you learned in pre-processing chapter.

Dataset description : 

The provided dataset contains the billing history of the Tunisian electricity and gas company's customers from 2005 to 2019.

➡️ Dataset link

https://i.imgur.com/AaBqRR5.png

 


Instructions

Load the dataset, display the ten first lines, store the results in a variable called 'client_0_bills'.
What is the data type of the 'client_0_bills' variable ?
Display the general information of the dataset and try to answer the following questions : 
How many rows and columns do we have in this dataset ?
How many categorical features are present in the dataset ?
How much memory space does the dataset consume ?
Inspect the dataset for potential missing values.
Select your strategy to handle missing values, and tell us why you had made that choice.
Run a descriptive analysis on numeric features (columns).
Select the bills records for the client with an id ='train_Client_0', using 2 methods.
Transform the 'counter_type' feature to a numeric variable using the encoder of your choice.
Delete the 'counter_statue' feature from the Dataframe




import warnings
warnings.filterwarnings('ignore')

In [15]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [17]:
# Load the dataset
df = pd.read_csv('Downloads/STEG_BILLING_HISTORY.csv')

# Display the first ten lines
client_0_bills = df.head(10)

client_0_bills

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
5,train_Client_0,2017-07-17,11,1335667.0,0,207,9.0,1,314,0,0,0,15638,15952,8,ELEC
6,train_Client_0,2018-12-07,11,1335667.0,0,207,9.0,1,541,0,0,0,15952,16493,12,ELEC
7,train_Client_0,2019-03-19,11,1335667.0,0,207,9.0,1,585,0,0,0,16493,17078,8,ELEC
8,train_Client_0,2011-07-22,11,1335667.0,0,203,9.0,1,1200,186,0,0,7770,9156,4,ELEC
9,train_Client_0,2011-11-22,11,1335667.0,0,203,6.0,1,1082,0,0,0,9156,10238,4,ELEC

In [18]:
# Check the data type of 'client_0_bills'
type(client_0_bills)

# Display general information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4476749 entries, 0 to 4476748
Data columns (total 16 columns):
 #   Column                Dtype
---  ------                -----
 0   client_id             object
 1   invoice_date          object
 2   tarif_type            int64
 3   counter_number        float64
 4   counter_statue        object
 5   counter_code          int64
 6   reading_remarque      float64
 7   counter_coefficient   int64
 8   consommation_level_1  int64
 9   consommation_level_2  int64
 10  consommation_level_3  int64
 11  consommation_level_4  int64
 12  old_index             int64
 13  new_index             int64
 14  months_number         int64
 15  counter_type          object
dtypes: float64(2), int64(10), object(4)
memory usage: 546.5+ MB

In [21]:
missing_values = df.isnull().sum()
missing_values

client_id                  0
invoice_date               0
tarif_type                 0
counter_number            48
counter_statue             0
counter_code               0
reading_remarque        4531
counter_coefficient        0
consommation_level_1       0
consommation_level_2       0
consommation_level_3       0
consommation_level_4       0
old_index                  0
new_index                  0
months_number              0
counter_type               0
dtype: int64

In [23]:
df_describe = df.describe().T
df_describe

df.describe(include = 'O').T

                  count  unique                  top     freq
client_id       4476749  135493  train_Client_116878      439
invoice_date    4476749    8275           2019-03-09     4127
counter_statue  4476749      16                    0  4346960
counter_type    4476749       2                 ELEC  3079406

In [24]:
# Missing values in counter_number by counter_type
missing_counter_by_type = df[df['counter_number'].isnull()]['counter_type'].value_counts()
print(missing_counter_by_type)

# Missing values in reading_remarque by counter_type
missing_reading_by_type = df[df['reading_remarque'].isnull()]['counter_type'].value_counts()
print(missing_reading_by_type)

counter_type
ELEC    42
GAZ      6
Name: count, dtype: int64
counter_type
ELEC    3091
GAZ     1440
Name: count, dtype: int64

In [27]:
# Check the relationship between missing values in 'counter_number' and 'client_id'
missing_counter_number = df[df['counter_number'].isnull()]

# Group by 'client_id' and count missing values
client_missing_counter = missing_counter_number.groupby('client_id').size()

client_missing_counter

client_id
train_Client_100692    1
train_Client_101420    1
train_Client_105565    1
train_Client_107280    1
train_Client_111438    1
train_Client_111922    1
train_Client_116384    1
train_Client_12409     1
train_Client_124505    1
train_Client_125948    1
train_Client_126772    1
train_Client_128649    1
train_Client_128891    1
train_Client_131022    1
train_Client_132167    1
train_Client_133547    1
train_Client_14251     1
train_Client_1602      1
train_Client_18501     1
train_Client_21581     1
train_Client_2292      1
train_Client_25710     1
train_Client_49150     1
train_Client_51432     1
train_Client_53761     1
train_Client_57024     1
train_Client_57474     1
train_Client_58004     1
train_Client_62418     1
train_Client_67247     1
train_Client_68243     1
train_Client_68317     1
train_Client_69248     1
train_Client_715       1
train_Client_72869     1
train_Client_73948     1
train_Client_75543     1
train_Client_78098     1
train_Client_78867     1
train_Client_85396     1
train_Client_86644     1
train_Client_87464     1
train_Client_87851     1
train_Client_87961     1
train_Client_91409     1
train_Client_92171     1
train_Client_93672     1
train_Client_98442     1
dtype: int64

In [29]:
# Missing values in reading_remarque
missing_reading_remarque = df[df['reading_remarque'].isnull()]
missing_by_client_reading = missing_reading_remarque['client_id'].value_counts()
missing_by_client_reading

client_id
train_Client_95470     3
train_Client_119751    3
train_Client_41026     2
train_Client_104481    2
train_Client_66981     2
                      ..
train_Client_19615     1
train_Client_19619     1
train_Client_19632     1
train_Client_19688     1
train_Client_99947     1
Name: count, Length: 4416, dtype: int64

In [31]:
# Let's group by 'client_id' and calculate aggregates for 'counter_number' to see the distrubution
client_counter_number_ranges = df.groupby('client_id')['counter_number'].agg(['min', 'max', 'mean', 'median']).reset_index()

client_counter_number_ranges

# Run a descriptive statistics on it
client_counter_number_ranges.describe()

                min           max          mean        median
count  1.354930e+05  1.354930e+05  1.354930e+05  1.354930e+05
mean   6.279163e+11  1.053179e+12  6.909203e+11  6.483284e+11
std    3.739104e+12  4.838268e+12  3.789278e+12  3.788251e+12
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%    6.117100e+04  3.441970e+05  2.622571e+05  1.779990e+05
50%    2.545850e+05  8.464130e+05  6.691836e+05  5.448130e+05
75%    7.416250e+05  4.903468e+06  2.611921e+06  1.194200e+06
max    2.739110e+13  2.798115e+13  2.739110e+13  2.739110e+13

In [33]:
# Calculate mean for each client 
client_counter_number_ranges = df.groupby('client_id')['counter_number'].agg(['mean']).reset_index()

# Create a dictionary mapping client_id to their mean counter_number
client_counter_number_dict = client_counter_number_ranges.set_index('client_id')['mean'].to_dict()

# Replace missing values in 'counter_number' with the corresponding client's mean
df['counter_number'] = df['counter_number'].fillna(df['client_id'].map(client_counter_number_dict))

# Verify that there are no more missing values in 'counter_number'
df['counter_number'].isnull().sum()

0

In [35]:
# Group by 'client_id' and calculate aggregates for 'reading_remarque' to see the distrubution
client_reading_remarque_ranges = df.groupby('client_id')['reading_remarque'].agg(['min', 'max', 'mean', 'median']).reset_index()
client_reading_remarque_ranges

# Run descriptive statistics
client_reading_remarque_ranges.describe()

                 min            max           mean         median
count  135487.000000  135487.000000  135487.000000  135487.000000
mean        6.318924       8.674441       7.398856       7.270162
std         1.511626       1.689160       1.511395       1.776078
min         5.000000       6.000000       6.000000       6.000000
25%         6.000000       9.000000       6.812500       6.000000
50%         6.000000       9.000000       7.285714       7.000000
75%         6.000000       9.000000       7.963300       8.500000
max       413.000000     413.000000     413.000000     413.000000

In [37]:
"""
# Calculate mean for each client 
client_reading_remarque_ranges = df.groupby('client_id')['reading_remarque'].agg(['mean']).reset_index()

# Create a dictionary mapping client_id to their mean reading_remarque
client_reading_remarque_dict = client_reading_remarque_ranges.set_index('client_id')['mean'].to_dict()

# Replace missing values in 'reading_remarque' with the corresponding client's mean
df['reading_remarque'] = df['reading_remarque'].fillna(df['client_id'].map(client_reading_remarque_dict))

# Verify that there are no more missing values in 'reading_remarque'
df['reading_remarque'].isnull().sum()

"""

"\n# Calculate mean for each client \nclient_reading_remarque_ranges = df.groupby('client_id')['reading_remarque'].agg(['mean']).reset_index()\n\n# Create a dictionary mapping client_id to their mean reading_remarque\nclient_reading_remarque_dict = client_reading_remarque_ranges.set_index('client_id')['mean'].to_dict()\n\n# Replace missing values in 'reading_remarque' with the corresponding client's mean\ndf['reading_remarque'] = df['reading_remarque'].fillna(df['client_id'].map(client_reading_remarque_dict))\n\n# Verify that there are no more missing values in 'reading_remarque'\ndf['reading_remarque'].isnull().sum()\n\n"

In [39]:
# Replace missing values in 'reading_remarque' with the corresponding client's mean
df['reading_remarque'] = df.groupby('client_id')['reading_remarque'].transform(
    lambda x: x.fillna(x.mean())
)

# Verify that there are no more missing values in 'reading_remarque'
df['reading_remarque'].isnull().sum()

6

In [40]:
# Checking for the 6 rows that were left
df[df['reading_remarque'].isnull()]

df[df['client_id'] == 'train_Client_15599']

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
1382561,train_Client_15599,2019-06-26,11,2.718110e+13,0,203,NaN,1,0,0,0,0,0,0,4,ELEC

In [41]:
df[df['client_id'] == 'train_Client_74123']

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
3521832,train_Client_74123,2017-06-03,10,2728751.0,0,202,NaN,1,0,0,0,0,4726,4726,15,ELEC

In [42]:
# The mean of 'reading_remarque' where 'counter_type' == 'ELEC'
mean_reading_remarque_elec = df[df['counter_type'] == 'ELEC']['reading_remarque'].mean()

# Replace the remaining missing 'reading_remarque' values with the calculated mean
df['reading_remarque'] = df['reading_remarque'].fillna(mean_reading_remarque_elec)

# Verify the changes
df['reading_remarque'].isnull().sum()

0

In [43]:
df_describe2 = df.describe().T
df_describe2

,count,mean,std,min,25%,50%,75%,max
tarif_type,4476749.0,2.012804e+01,1.347256e+01,8.0,11.0,11.0,40.0,4.500000e+01
counter_number,4476749.0,1.230593e+11,1.657268e+12,0.0,121108.0,494561.0,1115161.0,2.798115e+13
counter_code,4476749.0,1.724884e+02,1.338871e+02,0.0,5.0,203.0,207.0,6.000000e+02
reading_remarque,4476749.0,7.321708e+00,1.571353e+00,5.0,6.0,8.0,9.0,4.130000e+02
counter_coefficient,4476749.0,1.003040e+00,3.083466e-01,0.0,1.0,1.0,1.0,5.000000e+01
consommation_level_1,4476749.0,4.109795e+02,7.573080e+02,0.0,79.0,274.0,600.0,9.999100e+05
consommation_level_2,4476749.0,1.093225e+02,1.220123e+03,0.0,0.0,0.0,0.0,9.990730e+05
consommation_level_3,4476749.0,2.030620e+01,1.574239e+02,0.0,0.0,0.0,0.0,6.449200e+04
consommation_level_4,4476749.0,5.292588e+01,8.754725e+02,0.0,0.0,0.0,0.0,5.479460e+05
old_index,4476749.0,1.776700e+04,4.036693e+04,0.0,1791.0,7690.0,21660.0,2.800280e+06
new_index,4476749.0,1.834970e+04,4.095321e+04,0.0,2056.0,8192.0,22343.0,2.870972e+06
months_number,4476749.0,4.483095e+01,3.128335e+03,0.0,4.0,4.0,4.0,6.366240e+05

In [49]:
# Method 2: Using the query() method
client_0_bills_method_2 = df.query("client_id == 'train_Client_0'")

# Display the result
client_0_bills_method_2

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,ELEC
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,ELEC
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,ELEC
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,ELEC
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,ELEC
5,train_Client_0,2017-07-17,11,1335667.0,0,207,9.0,1,314,0,0,0,15638,15952,8,ELEC
6,train_Client_0,2018-12-07,11,1335667.0,0,207,9.0,1,541,0,0,0,15952,16493,12,ELEC
7,train_Client_0,2019-03-19,11,1335667.0,0,207,9.0,1,585,0,0,0,16493,17078,8,ELEC
8,train_Client_0,2011-07-22,11,1335667.0,0,203,9.0,1,1200,186,0,0,7770,9156,4,ELEC
9,train_Client_0,2011-11-22,11,1335667.0,0,203,6.0,1,1082,0,0,0,9156,10238,4,ELEC
10,train_Client_0,2008-11-25,11,1335667.0,0,203,6.0,1,174,0,0,0,5417,5591,4,ELEC
11,train_Client_0,2012-07-23,11,1335667.0,0,203,6.0,1,628,0,0,0,10780,11408,4,ELEC
12,train_Client_0,2012-11-29,11,1335667.0,0,203,6.0,1,886,0,0,0,11408,12294,4,ELEC
13,train_Client_0,2013-07-22,11,1335667.0,0,203,8.0,1,147,0,0,0,13983,14130,4,ELEC
14,train_Client_0,2014-07-18,11,1335667.0,0,203,8.0,1,99,0,0,0,14384,14483,4,ELEC
15,train_Client_0,2014-11-24,11,1335667.0,0,203,8.0,1,141,0,0,0,14483,14624,4,ELEC
16,train_Client_0,2015-11-18,11,1335667.0,0,207,9.0,1,217,0,0,0,14849,15066,4,ELEC
17,train_Client_0,2012-03-27,11,1335667.0,0,203,8.0,1,292,0,0,0,10488,10780,4,ELEC
18,train_Client_0,2011-03-30,11,1335667.0,0,203,6.0,1,497,0,0,0,7273,7770,4,ELEC
19,train_Client_0,2013-02-12,11,1335667.0,0,203,8.0,1,38,0,0,0,14264,14302,2,ELEC
20,train_Client_0,2010-07-22,11,1335667.0,0,203,6.0,1,278,0,0,0,6761,7039,4,ELEC
21,train_Client_0,2010-11-24,11,1335667.0,0,203,6.0,1,234,0,0,0,7039,7273,4,ELEC
22,train_Client_0,2005-10-17,11,1335667.0,0,203,6.0,1,124,0,0,0,3685,3809,4,ELEC
23,train_Client_0,2006-02-24,11,1335667.0,0,203,6.0,1,141,0,0,0,3809,3950,4,ELEC
24,train_Client_0,2006-06-23,11,1335667.0,0,203,6.0,1,162,0,0,0,3950,4112,4,ELEC
25,train_Client_0,2006-10-18,11,1335667.0,0,203,6.0,1,159,0,0,0,4112,4271,4,ELEC
26,train_Client_0,2007-06-27,11,1335667.0,0,203,6.0,1,240,0,0,0,4453,4693,4,ELEC
27,train_Client_0,2007-10-25,11,1335667.0,0,203,6.0,1,276,0,0,0,4693,4969,4,ELEC
28,train_Client_0,2007-02-26,11,1335667.0,0,203,6.0,1,182,0,0,0,4271,4453,4,ELEC
29,train_Client_0,2008-07-28,11,1335667.0,0,203,6.0,1,171,0,0,0,5246,5417,4,ELEC
30,train_Client_0,2009-01-04,11,1335667.0,0,203,6.0,1,315,0,0,0,5591,5906,4,ELEC
31,train_Client_0,2009-07-27,11,1335667.0,0,203,6.0,1,312,0,0,0,5906,6218,4,ELEC
32,train_Client_0,2009-11-24,11,1335667.0,0,203,6.0,1,267,0,0,0,6218,6485,4,ELEC
33,train_Client_0,2010-03-29,11,1335667.0,0,203,6.0,1,276,0,0,0,6485,6761,4,ELEC
34,train_Client_0,2008-01-04,11,1335667.0,0,203,6.0,1,277,0,0,0,4969,5246,4,ELEC

In [51]:
# Using One-Hot Encoding
df_one_hot = pd.get_dummies(df, columns=['counter_type'], prefix='counter_type')

# Display the result
df_one_hot.head()

,client_id,invoice_date,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type_ELEC,counter_type_GAZ
0,train_Client_0,2014-03-24,11,1335667.0,0,203,8.0,1,82,0,0,0,14302,14384,4,True,False
1,train_Client_0,2013-03-29,11,1335667.0,0,203,6.0,1,1200,184,0,0,12294,13678,4,True,False
2,train_Client_0,2015-03-23,11,1335667.0,0,203,8.0,1,123,0,0,0,14624,14747,4,True,False
3,train_Client_0,2015-07-13,11,1335667.0,0,207,8.0,1,102,0,0,0,14747,14849,4,True,False
4,train_Client_0,2016-11-17,11,1335667.0,0,207,9.0,1,572,0,0,0,15066,15638,12,True,False

In [53]:
# Delete the 'counter_statue' column from the DataFrame
df_one_hot = df_one_hot.drop('counter_statue', axis=1)

# Verify the column has been removed
df_one_hot.head()

,client_id,invoice_date,tarif_type,counter_number,counter_code,reading_remarque,counter_coefficient,consommation_level_1,consommation_level_2,consommation_level_3,consommation_level_4,old_index,new_index,months_number,counter_type_ELEC,counter_type_GAZ
0,train_Client_0,2014-03-24,11,1335667.0,203,8.0,1,82,0,0,0,14302,14384,4,True,False
1,train_Client_0,2013-03-29,11,1335667.0,203,6.0,1,1200,184,0,0,12294,13678,4,True,False
2,train_Client_0,2015-03-23,11,1335667.0,203,8.0,1,123,0,0,0,14624,14747,4,True,False
3,train_Client_0,2015-07-13,11,1335667.0,207,8.0,1,102,0,0,0,14747,14849,4,True,False
4,train_Client_0,2016-11-17,11,1335667.0,207,9.0,1,572,0,0,0,15066,15638,12,True,False